// schedules
export const SET_NEW_DATE = 'SET_NEW_DATE'
export const SET_EXPANDED_DATE = 'SET_EXPANDED_DATE'
export const SET_NEW_SCHEDULES = 'SET_NEW_SCHEDULES'

// places
export const SELECT_PLACE = 'SELECT_PLACE'
export const DESELECT_PLACE = 'DESELECT_PLACE'
export const GET_PLACES = 'GET_PLACES'

// events
export const GET_EVENTS_SCHEDULES = 'GET_EVENTS_SCHEDULES'
export const SELECT_EVENT = 'SELECT_EVENT'
export const DESELECT_EVENT = 'DESELECT_EVENT'

// presets
export const SWITCH_EDITION_MODE = 'SWITCH_EDITION_MODE'
export const SET_NEW_PRESET = 'SET_NEW_PRESET'
export const SET_CURRENT_PRESET = 'SET_CURRENT_PRESET'
export const SAVE_NEW_PRESET = 'SAVE_NEW_PRESET'
export const REMOVE_NEW_PRESET = 'REMOVE_NEW_PRESET'
export const REMOVE_CURRENT_PRESET = 'REMOVE_CURRENT_PRESET'
export const GET_PRESETS = 'GET_PRESETS'
export const SELECT_PRESET = 'SELECT_PRESET'
export const DELETE_PRESET = 'DELETE_PRESET'

// modals
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

// timestamps
export const GET_TIMESTAMPS_API = 'GET_TIMESTAMPS_API'
export const SET_NEW_DAYS = 'SET_NEW_DAYS'
export const SET_NEW_HOURS = 'SET_NEW_HOURS'
